/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    features: Feature;
    users: User;
    enquiries: Enquiry;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | ConversationHeroBlock
    | PartnerStripBlock
    | StatHeroBlock
    | LogoWallBlock
    | ProblemStatementBlock
    | PlatformLayersBlock
    | JourneyEngineBlock
    | ContextEngineBlock
    | SolutionGridBlock
    | ProductSuiteBlock
    | UseCasesBlock
    | BenefitsBlock
    | IntegrationsBlock
    | TrustPanelBlock
    | StatBandBlock
    | ContactFormBlock
    | HowItWorksBlock
    | ClosingCTABlock
    | FeatureThreadBlock
    | ArticleGridBlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConversationHeroBlock".
 */
export interface ConversationHeroBlock {
  /**
   * Optional. Short, e.g. "Omnichannel automation and reasoning".
   */
  eyebrow?: string | null;
  /**
   * Short and direct works best — around six to eight words.
   */
  headline: string;
  /**
   * One or two sentences explaining what the product does, in plain language.
   */
  subhead: string;
  primaryButtonLabel?: string | null;
  primaryButtonLink?: string | null;
  secondaryButtonLabel?: string | null;
  secondaryButtonLink?: string | null;
  /**
   * Short capability labels, e.g. "WhatsApp · Voice · Web". Two or three works best.
   */
  chips?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * For example "WhatsApp · Ayurvaid Hospitals · 11:42".
   */
  conversationLabel?: string | null;
  /**
   * One message per line. Start a line with "them:" for the customer, "us:" for the agent, and "tag:" for a system note at the end.
   */
  conversation?: string | null;
  /**
   * Optional. What fires behind the scenes, e.g. Booked, Paid, Reminder sent.
   */
  workflowSteps?:
    | {
        label: string;
        icon?: ('calendar' | 'card' | 'document' | 'message' | 'check') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Real, defensible figures only — these sit directly under the hero.
   */
  stats?:
    | {
        /**
         * e.g. 40%, 2.5x, 14+
         */
        value: string;
        /**
         * What the number means, in three or four words.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'conversationHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerStripBlock".
 */
export interface PartnerStripBlock {
  /**
   * For example: Powering conversational commerce across industries.
   */
  intro?: string | null;
  /**
   * Systems you connect to, set as text rather than logos — DocPulse, LeadSquared, WhatsApp Business API. This is not the client logo wall.
   */
  partners?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only claim a standard you actually meet — these are read closely by hospital IT.
   */
  badges?:
    | {
        /**
         * e.g. ABDM
         */
        name: string;
        /**
         * e.g. ready
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatHeroBlock".
 */
export interface StatHeroBlock {
  /**
   * Small line above the headline. A short category statement, e.g. "AI automation for patient journeys".
   */
  eyebrow?: string | null;
  /**
   * The main statement. Six to nine words works best.
   */
  headline: string;
  /**
   * One or two sentences explaining what the platform does and for whom.
   */
  subhead?: string | null;
  primaryLabel?: string | null;
  primaryLink?: string | null;
  /**
   * Leave empty to hide the second button.
   */
  secondaryLabel?: string | null;
  secondaryLink?: string | null;
  /**
   * Headline numbers. Use real, defensible figures - three works best.
   */
  stats?:
    | {
        /**
         * e.g. 40%, 2.5x, 14+
         */
        value: string;
        /**
         * What the number means, in three or four words.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock".
 */
export interface LogoWallBlock {
  /**
   * Short and plain, e.g. "Trusted by". Leave empty to hide.
   */
  label?: string | null;
  heading?: string | null;
  /**
   * One or two sentences. Leave empty to hide.
   */
  intro?: string | null;
  /**
   * Logos are more convincing, but every file needs a transparent background. Switch to logos once you have proper assets for all of them.
   */
  display?: ('wordmarks' | 'logos') | null;
  /**
   * The name is always used. A logo file is only needed when the display mode above is set to logos.
   */
  logos?:
    | {
        /**
         * Shown as text in wordmark mode, and used as the image alt text in logo mode. Keep it short — long names crowd the row.
         */
        name: string;
        /**
         * Transparent PNG or SVG. Only used in logo mode.
         */
        logo?: (string | null) | Media;
        /**
         * Logo mode only. Leave at 100 unless a logo looks too big or small next to the others. Round crests usually need 130–150.
         */
        scale?: number | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoWall';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemStatementBlock".
 */
export interface ProblemStatementBlock {
  /**
   * e.g. The problem
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  problems?:
    | {
        /**
         * The short name of the problem, e.g. "Siloed systems".
         */
        title: string;
        /**
         * One sentence on what it costs them.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small italic line under the list. Optional.
   */
  note?: string | null;
  /**
   * The disconnected systems shown in the panel, e.g. Ops, CRM, Payments.
   */
  systems?:
    | {
        name: string;
        /**
         * e.g. Orders · status
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. records unlinked · context lost between steps
   */
  gapLine?: string | null;
  /**
   * e.g. NeuronCx unifies them into
   */
  resolutionLine?: string | null;
  /**
   * Shown in green, e.g. one customer context
   */
  resolutionHighlight?: string | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'problemStatement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformLayersBlock".
 */
export interface PlatformLayersBlock {
  /**
   * e.g. The platform
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * e.g. Scroll to move through the stack — each layer builds on the one before it.
   */
  intro?: string | null;
  /**
   * Each one takes a screen as the visitor scrolls, so keep the list short.
   */
  layers?:
    | {
        title: string;
        description: string;
        /**
         * Optional, e.g. Core or Adjacent.
         */
        tag?: string | null;
        icon?: ('message' | 'bolt' | 'layers' | 'gauge' | 'plug') | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'platformLayers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyEngineBlock".
 */
export interface JourneyEngineBlock {
  /**
   * e.g. A live journey
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  /**
   * The stages of the journey, defined once. Every industry below uses these same stages in this same order.
   */
  stages?:
    | {
        /**
         * e.g. Enquiry
         */
        label: string;
        icon?: ('message' | 'check' | 'calendar' | 'card' | 'document' | 'chat' | 'refresh') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * One tab per industry. Add one detail per stage, in the same order as the stages above — the first detail belongs to the first stage.
   */
  industries?:
    | {
        /**
         * Tab label, e.g. Diagnostics
         */
        name: string;
        details?:
          | {
              /**
               * e.g. Recovery
               */
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'journeyEngine';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContextEngineBlock".
 */
export interface ContextEngineBlock {
  /**
   * e.g. Why NeuronCx
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  points?:
    | {
        /**
         * e.g. Grounded, not scripted.
         */
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Customer 360
   */
  calloutTerm?: string | null;
  /**
   * e.g. is the shared memory every agent and channel reads from.
   */
  calloutText?: string | null;
  centreLabel?: string | null;
  /**
   * Spaced evenly around the centre automatically. Six to eight looks best; more than that and the labels crowd.
   */
  satellites?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contextEngine';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionGridBlock".
 */
export interface SolutionGridBlock {
  /**
   * e.g. Solutions
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  /**
   * Each group is a row of cards under its own small heading, e.g. By journey.
   */
  groups?:
    | {
        /**
         * e.g. By journey
         */
        title: string;
        items?:
          | {
              label: string;
              /**
               * Optional. Leave empty and the card is plain text rather than a link — better than linking to a page that does not exist yet.
               */
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductSuiteBlock".
 */
export interface ProductSuiteBlock {
  label?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * Keep these matched to the main navigation so the site says one thing.
   */
  products?:
    | {
        name: string;
        /**
         * One or two plain sentences. Say what it does, not why it is good.
         */
        summary?: string | null;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        linkLabel?: string | null;
        /**
         * For example /omnichannel-cx
         */
        linkHref?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productSuite';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UseCasesBlock".
 */
export interface UseCasesBlock {
  label?: string | null;
  heading?: string | null;
  intro?: string | null;
  cases?:
    | {
        /**
         * For example Hospitals, Diagnostics, Universities.
         */
        sector?: string | null;
        /**
         * Name the job, e.g. "Appointment booking and rescheduling".
         */
        title: string;
        description?: string | null;
        /**
         * A result, ideally measured. Leave empty rather than inventing one.
         */
        outcome?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'useCases';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  label?: string | null;
  heading?: string | null;
  /**
   * Say what changes for the customer, not what the software contains.
   */
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsBlock".
 */
export interface IntegrationsBlock {
  label?: string | null;
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        name: string;
        /**
         * What flows between the two systems, in plain words.
         */
        summary?: string | null;
        /**
         * Transparent PNG or SVG. Leave empty to show the name only.
         */
        logo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * For example: anything else connects over our REST API and webhooks.
   */
  footnote?: string | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integrations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustPanelBlock".
 */
export interface TrustPanelBlock {
  /**
   * e.g. Deployment & trust
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  /**
   * Claims here are read closely during procurement — only state what you can evidence.
   */
  cards?:
    | {
        title: string;
        description: string;
        icon?: ('shield' | 'lock' | 'globe' | 'shieldCheck' | 'server' | 'eye') | null;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustPanel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatBandBlock".
 */
export interface StatBandBlock {
  /**
   * Use figures you could defend if a prospect asked how you measured them. Three or four works best.
   */
  stats?:
    | {
        /**
         * e.g. 4 industries, 1,300+
         */
        value: string;
        /**
         * What the number means.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Use it to say how the figures are measured or over what period — not to disclaim them.
   */
  note?: string | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  label?: string | null;
  heading?: string | null;
  intro?: string | null;
  buttonLabel?: string | null;
  successMessage?: string | null;
  showMessageField?: boolean | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock".
 */
export interface HowItWorksBlock {
  /**
   * Small line above the heading.
   */
  label?: string | null;
  /**
   * The section heading.
   */
  heading: string;
  intro?: string | null;
  /**
   * Numbered automatically. Three steps is the readable maximum for most visitors.
   */
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to hide the button.
   */
  ctaLabel?: string | null;
  ctaLink?: string | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'howItWorks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingCTABlock".
 */
export interface ClosingCTABlock {
  /**
   * The last thing a visitor reads. Make it a clear ask.
   */
  heading: string;
  subhead?: string | null;
  primaryLabel?: string | null;
  primaryLink?: string | null;
  secondaryLabel?: string | null;
  secondaryLink?: string | null;
  /**
   * Optional, shown in italics. Short — a line, not a sentence.
   */
  tagline?: string | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'closingCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureThreadBlock".
 */
export interface FeatureThreadBlock {
  /**
   * Optional. Leave empty to show the features with no heading.
   */
  heading?: string | null;
  /**
   * Leave empty to show all four. Pick one when this sits on a product page.
   */
  categories?: ('omnichannel-cx' | 'knowledge-base' | 'user-intelligence' | 'integrations')[] | null;
  /**
   * Only published features are shown, in the order set on each feature. One per category suits the home page; three or four suits a product page.
   */
  limitPerCategory?: number | null;
  /**
   * Tick this when the block is on the category page it would link to — otherwise every entry links back to the page the visitor is already reading.
   */
  hideCategoryLinks?: boolean | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureThread';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleGridBlock".
 */
export interface ArticleGridBlock {
  /**
   * Heading above the articles.
   */
  heading?: string | null;
  /**
   * Optional line under the heading.
   */
  intro?: string | null;
  /**
   * How many articles to show. The most recently published appear first.
   */
  limit?: number | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  background?: ('default' | 'white' | 'cloud' | 'navy' | 'crimson') | null;
  width?: ('default' | 'narrow' | 'wide' | 'full') | null;
  spacingTop?: ('default' | 'none' | 'sm' | 'lg') | null;
  spacingBottom?: ('default' | 'none' | 'sm' | 'lg') | null;
  align?: ('default' | 'left' | 'center') | null;
  /**
   * Keeps the block and its content but removes it from the page.
   */
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * Short product capability descriptions. These appear in the sections on the home page and on the platform pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: string;
  /**
   * The name of the capability, as a reader would say it. Keep it under 60 characters.
   */
  title: string;
  /**
   * Which part of the platform this belongs to. Decides where it appears on the site.
   */
  category: 'omnichannel-cx' | 'knowledge-base' | 'user-intelligence' | 'integrations';
  /**
   * One or two plain sentences describing what this does for the customer. Shown in listings and on the home page.
   */
  summary: string;
  /**
   * Optional longer explanation, shown on the feature page itself.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional illustration. Landscape images work best.
   */
  image?: (string | null) | Media;
  /**
   * Lower numbers appear first within a category.
   */
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Enquiries submitted from the website contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  name: string;
  company?: string | null;
  email: string;
  mobile?: string | null;
  message?: string | null;
  /**
   * The page the form was submitted from.
   */
  sourcePage?: string | null;
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'features';
        value: string | Feature;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        conversationHero?: T | ConversationHeroBlockSelect<T>;
        partnerStrip?: T | PartnerStripBlockSelect<T>;
        statHero?: T | StatHeroBlockSelect<T>;
        logoWall?: T | LogoWallBlockSelect<T>;
        problemStatement?: T | ProblemStatementBlockSelect<T>;
        platformLayers?: T | PlatformLayersBlockSelect<T>;
        journeyEngine?: T | JourneyEngineBlockSelect<T>;
        contextEngine?: T | ContextEngineBlockSelect<T>;
        solutionGrid?: T | SolutionGridBlockSelect<T>;
        productSuite?: T | ProductSuiteBlockSelect<T>;
        useCases?: T | UseCasesBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        integrations?: T | IntegrationsBlockSelect<T>;
        trustPanel?: T | TrustPanelBlockSelect<T>;
        statBand?: T | StatBandBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        howItWorks?: T | HowItWorksBlockSelect<T>;
        closingCta?: T | ClosingCTABlockSelect<T>;
        featureThread?: T | FeatureThreadBlockSelect<T>;
        articleGrid?: T | ArticleGridBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConversationHeroBlock_select".
 */
export interface ConversationHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subhead?: T;
  primaryButtonLabel?: T;
  primaryButtonLink?: T;
  secondaryButtonLabel?: T;
  secondaryButtonLink?: T;
  chips?:
    | T
    | {
        label?: T;
        id?: T;
      };
  conversationLabel?: T;
  conversation?: T;
  workflowSteps?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerStripBlock_select".
 */
export interface PartnerStripBlockSelect<T extends boolean = true> {
  intro?: T;
  partners?:
    | T
    | {
        name?: T;
        id?: T;
      };
  badges?:
    | T
    | {
        name?: T;
        suffix?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatHeroBlock_select".
 */
export interface StatHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subhead?: T;
  primaryLabel?: T;
  primaryLink?: T;
  secondaryLabel?: T;
  secondaryLink?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock_select".
 */
export interface LogoWallBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  display?: T;
  logos?:
    | T
    | {
        name?: T;
        logo?: T;
        scale?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemStatementBlock_select".
 */
export interface ProblemStatementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  problems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  note?: T;
  systems?:
    | T
    | {
        name?: T;
        detail?: T;
        id?: T;
      };
  gapLine?: T;
  resolutionLine?: T;
  resolutionHighlight?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformLayersBlock_select".
 */
export interface PlatformLayersBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  layers?:
    | T
    | {
        title?: T;
        description?: T;
        tag?: T;
        icon?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyEngineBlock_select".
 */
export interface JourneyEngineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  stages?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        name?: T;
        details?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContextEngineBlock_select".
 */
export interface ContextEngineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  points?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  calloutTerm?: T;
  calloutText?: T;
  centreLabel?: T;
  satellites?:
    | T
    | {
        label?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionGridBlock_select".
 */
export interface SolutionGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  groups?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductSuiteBlock_select".
 */
export interface ProductSuiteBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  products?:
    | T
    | {
        name?: T;
        summary?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        linkLabel?: T;
        linkHref?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UseCasesBlock_select".
 */
export interface UseCasesBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  cases?:
    | T
    | {
        sector?: T;
        title?: T;
        description?: T;
        outcome?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsBlock_select".
 */
export interface IntegrationsBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        name?: T;
        summary?: T;
        logo?: T;
        id?: T;
      };
  footnote?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustPanelBlock_select".
 */
export interface TrustPanelBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  buttonLabel?: T;
  buttonHref?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatBandBlock_select".
 */
export interface StatBandBlockSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  note?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  buttonLabel?: T;
  successMessage?: T;
  showMessageField?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock_select".
 */
export interface HowItWorksBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingCTABlock_select".
 */
export interface ClosingCTABlockSelect<T extends boolean = true> {
  heading?: T;
  subhead?: T;
  primaryLabel?: T;
  primaryLink?: T;
  secondaryLabel?: T;
  secondaryLink?: T;
  tagline?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureThreadBlock_select".
 */
export interface FeatureThreadBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?: T;
  limitPerCategory?: T;
  hideCategoryLinks?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleGridBlock_select".
 */
export interface ArticleGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  limit?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  background?: T;
  width?: T;
  spacingTop?: T;
  spacingBottom?: T;
  align?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  summary?: T;
  body?: T;
  image?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  mobile?: T;
  message?: T;
  sourcePage?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Each item is either a plain link, or a dropdown if you add columns to it. Only add links to pages that exist — a menu full of dead links is worse than a short menu.
   */
  navItems?:
    | {
        label: string;
        /**
         * Where this goes when clicked, e.g. /integrations. Leave empty if it only opens a dropdown.
         */
        href?: string | null;
        /**
         * Leave empty for a plain link. Add one to four columns to turn this into a dropdown.
         */
        columns?:
          | {
              heading?: string | null;
              links?:
                | {
                    label: string;
                    /**
                     * For example /omnichannel-cx
                     */
                    href: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  signInLabel?: string | null;
  signInHref?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * One or two sentences under the logo describing what NeuronCx does.
   */
  tagline?: string | null;
  /**
   * Groups of links on the right side of the footer, e.g. Platform and Company.
   */
  columns?:
    | {
        /**
         * Heading for this group of links.
         */
        title: string;
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact email shown in the footer.
   */
  email?: string | null;
  /**
   * Contact phone number shown in the footer.
   */
  phone?: string | null;
  /**
   * Small links on the bottom line, e.g. Terms and Privacy.
   */
  legalItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  signInLabel?: T;
  signInHref?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  email?: T;
  phone?: T;
  legalItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'features';
          value: string | Feature;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}